name: Pull Repo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Create directory
        run: mkdir -p /home/runner/work/touhou-public.github.io/touhou-public.github.io/WeHou

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: Touhou-Public/WeHou
          ref: master
          path: WeHou

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: WeHou