name: upload to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create directory
        run: mkdir -p /home/runner/work/touhou-public.github.io/touhou-public.github.io/WeHou

      - name: Build and deploy
        uses: JamesIves/github-pages-deploy-action@4.1.2
        with:
          branch: gh-pages
          folder: WeHou
